apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-client-list-flights
  labels:
    app: flight
    component: flight-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight-client-list-flights
          image: flight-client:latest
          imagePullPolicy: Never
          env:
            - name: ROUTINE
              value: list_flights
            - name: ENDPOINT
              value: grpc://flight-server:8815
            - name: PYTHONUNBUFFERED
              value: "1"
